### ISSUE TITLE
getElementsByTagName() error

### ISSUE THREAD

**Issue by rubsilva** [candy-chat/xmpp-prebind-php#7]
Hello

I'm trying to get the prebind working but it's giving the following error:

Fatal error: Call to a member function getElementsByTagName() on a non-object in /var/www/converse/XmppPrebind.php on line 128

I am hoping that someone can help me figuring out what is the problem.
Thank you

**Comment by gbonvehi** [comment]
@rubsilva probably there was an error when connecting, my pull request #9  that was just merged will throw an exception when that happens instead of giving that fatal error.
